# Generated by Django 4.0.1 on 2024-04-20 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
            ],
            options={
                'db_table': 'clothes',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'manufacturers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'styles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingItemStyle',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('clothingitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothingitem')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.style')),
            ],
            options={
                'db_table': 'clothes_styles',
            },
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to='clothes.manufacturer'),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='styles',
            field=models.ManyToManyField(through='clothes.ClothingItemStyle', to='clothes.Style'),
        ),
    ]
