# Generated by Django 4.0.1 on 2024-04-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=9.99)),
                ('quantity', models.IntegerField(default=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products/')),
                ('type', models.CharField(choices=[('book', 'book'), ('clothes', 'clothes'), ('mobile', 'mobile')], max_length=20)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
    ]
