# Generated by Django 4.0.1 on 2024-04-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('Canceled', 'Canceled'), ('Arrived', 'Arrived'), ('Transporting', 'Transporting'), ('Hold', 'Hold')], default='Transporting', max_length=30)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.FloatField()),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_timestamp'],
            },
        ),
    ]
