# Generated by Django 4.0.1 on 2024-05-30 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('hire_date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('salary', models.BigIntegerField()),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_desk', models.CharField(max_length=100)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='general.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=100)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='general.staff')),
            ],
        ),
    ]
