# Generated by Django 4.0.1 on 2024-04-20 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothes', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileType',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mobile_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
                ('rom_size', models.IntegerField(default=64000)),
                ('ram_size', models.IntegerField(default=6000)),
                ('display_resolution', models.CharField(default='720 x 1080', max_length=50)),
                ('chip', models.CharField(default='Standard chip', max_length=50)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='clothes.manufacturer')),
                ('mobile_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='mobile.mobiletype')),
            ],
            options={
                'db_table': 'mobiles',
                'ordering': ['product__name'],
            },
        ),
    ]
