# Generated by Django 4.0.1 on 2024-04-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('Cash on Delivery', 'Cash on Delivery')], max_length=30)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Canceled', 'Canceled'), ('Partially Paid', 'Partially Paid'), ('Expired', 'Expired')], max_length=50)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('security_code', models.CharField(blank=True, max_length=6, null=True)),
                ('paid_amount', models.FloatField(default=0.0)),
                ('debt_amount', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
