# Generated by Django 4.0.1 on 2024-04-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('order_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('product_id', models.BigIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'cart_items',
                'ordering': ['-date_added'],
            },
        ),
    ]
