# Generated by Django 4.0.1 on 2024-05-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.BigIntegerField()),
                ('doctor_id', models.BigIntegerField()),
                ('appointment_datetime', models.DateTimeField()),
                ('duration', models.CharField(max_length=30)),
                ('note', models.TextField()),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('status', models.CharField(default='Scheduled', max_length=30)),
            ],
        ),
    ]
