# Generated by Django 4.0.1 on 2024-04-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('shipping_address', models.TextField()),
                ('shipping_method', models.CharField(choices=[('Standard', 'Standard Shipping'), ('Air', 'Air Freight'), ('Sea', 'Sea Freight'), ('Express', 'Express Shipping'), ('Truck', 'Truck Delivery'), ('Mail', 'Mail Delivery'), ('Local', 'Local Delivery')], max_length=30)),
                ('estimated_delivery_date', models.DateField()),
                ('tracking_information', models.TextField(default='On the way', max_length=255)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('fee', models.FloatField()),
            ],
            options={
                'db_table': 'shipments',
                'ordering': ['-created_timestamp'],
            },
        ),
    ]
