# Generated by Django 4.0.1 on 2024-04-20 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='estimated_delivery_date',
            field=models.DateField(default=datetime.date(2024, 6, 1)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='fee',
            field=models.FloatField(default=1.99),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipping_method',
            field=models.CharField(choices=[('Standard', 'Standard Shipping'), ('Air', 'Air Freight'), ('Sea', 'Sea Freight'), ('Express', 'Express Shipping'), ('Truck', 'Truck Delivery'), ('Mail', 'Mail Delivery'), ('Local', 'Local Delivery')], default='Standard', max_length=30),
        ),
    ]
